<?php
	// file for displaying an error message on deleted sites
?>
<!DOCTYPE html>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>" />
	<!-- <script>
		window.location.href =   'https://blog.tokiomarine.com.br/vida-saudavel/';		
	</script> -->

<title><?php
	/*
	 * Print the <title> tag based on what is being viewed.
	 */
	global $page, $paged;
	wp_title( '|', true, 'right' );

	// Add the blog name.
	bloginfo( 'name' );

?></title>

<style>
	.content {
		width:500px;
		height:500px;
		margin:0 auto;
		background:#999;
		position:absolute;
		left:50%;
		top:50%;
		margin-left:-250px;
		margin-top:-250px;
		padding: 10px;
	}
	.content p {
		position: relative;
		top: 50%;
		transform: translateY(-50%);
		text-align: center;
		font-size: 18px;
		font-family: 'Helvetica Neue', Verdana, sans-serif;
	}
	a:link,
	a:visited {
		color: #fff;
		text-decoration: underline;
	}
	a:hover,
	a:active {
		color: #fff;
		text-decoration: none;
	}
</style>
<?php 


$arrayde = [
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/03/19/seguro-vida-mulher/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/03/19/cancer-colorretal/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/03/19/relogio-biologico/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/03/19/esteira-exercicios-em-casa/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/03/19/mulheres-luta-pela-igualdade/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/03/19/beneficios-propolis/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/02/26/dicionario-segures/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/02/26/pular-corda/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/02/26/ler/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/02/26/emocional-na-pandemia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/02/26/fone-de-ouvido/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/02/26/acucar-faz-mal/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/01/28/planejamento-financeiro/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/01/28/previna-se-da-dengue/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/01/28/meditacao/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/01/28/aplicativos-de-exercicios/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/01/28/sem-perder-o-foco/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2021/01/28/como-desinchar/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/12/08/bicicleta-ergometrica/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/12/07/excessos-de-fim-de-ano-2/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/12/07/check-up-concorra/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/12/07/minimalismo/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/12/07/doacoes-na-pandemia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/12/07/dezembro-laranja-prevencao/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/11/23/doencas-que-mais-matam/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/11/23/diabete-azul/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/11/23/exercicios-abdominais/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/11/23/doe-orgaos-salve-vidas/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/11/23/omega-3-gorduras-essenciais/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/11/20/novembro-azul-2/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/10/26/outubro-rosa-2/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/10/26/ocio-produtivo/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/10/26/medicina-preventiva/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/10/26/alimentos-saudaveis-para-criancas/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/10/26/exercicios-em-familia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/10/26/seguro-vida-reserva-financeira/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/09/17/alzheimer-prevencao/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/09/16/aplicativo-vida-saudavel-saude-ao-alcance-das-maos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/09/16/vamos-falar-sobre-depressao/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/09/16/exercicio-como-remedio/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/09/16/inteligencia-emocional-sabia-como-ter/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/09/16/depressao-alimentacao-como-aliada/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/08/13/novidades-do-seguro-vida-homem/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/08/13/agosto-dourado-doe-o-seu-leite/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/08/13/pets-conforto-emocional-em-tempos-de-pandemia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/08/13/faca-alongamento-o-seu-corpo-agradece/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/08/13/vencendo-a-ansiedade-em-tempos-de-covid-19/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/08/13/vitamina-d-vitamina-do-sol/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/07/16/covid-19-medo-de-ir-ao-hospital/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/07/16/seguro-vida-pme-tokio-marine/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/07/16/aumento-do-consumo-alcool-na-pandemia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/07/16/a-danca-como-remedio/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/07/16/campanha-agasalho-solidariedade/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/07/16/alimentacao-saudavel-inverno/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/06/12/va-de-bike/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/06/12/aplicativos-para-reunioes-virtuais-covid-19/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/06/10/cobertura-seguro-vida-coronavirus/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/06/10/doe-sangue-quarentena/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/06/10/planejamento-financeiro-covid-19/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/06/10/horta-casa-apartamento/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/05/08/telemedicina-einstein-conecta/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/05/08/alcool-gel-cuidado-acidentes/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/05/08/covid-19-cuidados-bem-estar/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/05/08/mascaras-protecao-duvidas/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/05/08/intestino-saudavel-fortalecimento-imunologico/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/05/08/yoga-corpo-mente-quarentena/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/04/01/seguro-vida-individual-tokio-marine-beneficios-ate-para-voce-que-esta-em-casa/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/04/01/saude-mental-em-tempos-de-quarentena/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/04/01/quarentena-como-dar-continuidade-ao-ensino-das-criancas/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/04/01/fique-em-casa-na-quarentena-mas-nao-fique-parado/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/04/01/home-office-na-quarentena/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/04/01/os-campeoes-da-imunidade-na-quarentena/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/03/12/transito-como-amenizar-os-efeitos-colaterais-causados-pelo-tempo-dentro-do-carro/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/03/12/beneficios-do-crossfit/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/03/12/como-tornar-a-alimentacao-saudavel-atrativa-para-as-criancas/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/03/12/transtorno-de-ansiedade-generalizada/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/03/12/prevencao-de-infeccoes-comuns-no-brasil/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/03/12/no-mes-da-mulher-reforcamos-as-grandes-conquistas-e-a-luta-por-igualdade-de-direitos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/02/13/einstein-conecta/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/02/13/fevereiro-roxo/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/02/13/caminhe-a-saude-agradece/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/02/12/a-musica-como-remedio/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/02/12/voce-esta-interessado-em-investir/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/02/12/carnaval-alimente-se-bem-para-cair-na-folia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/01/16/escola-segurada-seu-filho-protegido/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/01/16/cardapio-de-verao-2/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/01/16/os-beneficios-do-hobby/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/01/16/mergulhar-e-divertido-mas-e-coisa-seria/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/01/16/mindfulness/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2020/01/16/sarampo-e-caxumba-prevenir-e-o-melhor-remedio/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/12/17/voce-sabia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/12/11/de-olho-na-gordura-visceral/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/12/11/mes-da-luta-contra-a-aids/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/12/11/aproveite-a-praia-para-se-exercitar/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/12/11/metas-de-fim-de-ano/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/12/11/excessos-de-fim-de-ano/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/11/19/sete-bons-motivos-para-contratar-um-seguro/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/11/19/novembro-azul/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/11/19/a-importancia-de-dormir-bem/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/11/19/spinning/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/11/19/vencendo-a-compulsao-alimentar/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/11/19/as-maravilhas-da-dieta-mediterranea/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/10/14/vida-individual-e-vida-em-grupo/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/10/14/outubro-rosa/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/10/14/estendendo-a-mao/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/10/14/a-importancia-da-musculacao-ao-longo-da-vida/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/10/14/viver-conectado-interfere-no-seu-bem-estar/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/10/14/sodio-ele-e-necessario-sim/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/09/09/7-mitos-comuns-sobre-seguro-de-vida/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/09/06/21-de-setembro-dia-mundial-da-doenca-de-alzheimer/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/09/06/combate-ao-tabagismo/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/09/06/personal-trainer/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/09/06/sindrome-de-burnout/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/09/06/carboidrato-voce-pode-e-deve-comer/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/tokio-marine-acidentes-pessoais-escolar/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/seguro-de-vida-mulher/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/seguro-de-vida-individual/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/recolocacao-profissional-e-assistencia-em-decorrencia-de-atos-violentos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/vida-homem/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/inclusao-automatica-dos-filhos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/tokio-marine-acidentes-pessoais-individual/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/maio-amarelo-por-uma-nova-forma-de-encarar-o-transito/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/doar-sangue-um-ato-de-amor/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/fevereiro-e-mes-de-combate-ao-alcoolismo/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/vida-em-grupo-pequenas-e-medias-empresas/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/a-importancia-do-check-up-prevencao-e-cura/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/de-olho-no-outubro-rosa/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/dezembro-laranja-protecao-da-pele-e-coisa-seria/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/doe-sangue-voce-pode-salvar-uma-vida/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/medicina-preventiva-a-medicina-do-futuro/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/hipertensao-uma-doenca-cada-vez-mais-comum/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/tolerancia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/comprometimento-com-a-saude/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/envelhecer-bem/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/o-doce-poder-do-elogio-e-da-gratidao/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/1o-de-dezembro/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/outubro-mes-do-combate-a-obesidade/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/8-de-marco/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/historias-inspiradoras/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/planejamento-financeiro-familiar/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/09/a-importancia-da-consulta-medica-antes-da-academia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/os-habitos-que-construimos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/agua-e-vida/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/intolerancia-a-lactose/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/ceia-de-natal-uma-mesa-repleta-de-tradicoes/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/cardapio-de-verao/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/alimentos-termogenicos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/mitos-e-verdades-sobre-a-gordura/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/obesidade-infantil-arme-se-contra-ela/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/o-prato-ideal/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/restricoes-alimentares-modismos-ou-verdade/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/frutas-a-farmacia-em-casa/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/exercicio-em-grupo-e-melhor/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/natacao-descubra-bons-motivos-para-correr-para-a-piscina/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/esportes-de-verao-pratique-sem-sustos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/escolhendo-a-academia/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/exercicios-ao-ar-livre/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/pilates/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/alongue-se/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/conheca-os-beneficios-dos-exercicios-funcionais/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/todo-mundo-tem-dez-minutos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/sua-excelencia-o-colaborador/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/maio-mes-de-todas-as-maes/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/por-que-viajar-faz-bem-a-saude/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/meio-ambiente-o-que-podemos-fazer-por-ele/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/declare-guerra-ao-estresse/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/seu-animal-de-estimacao-faz-bem-a-saude/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/o-poder-das-confraternizacoes-de-fim-de-ano/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/05/precisamos-falar-sobre-depressao/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/02/cuidando-da-sua-saude-mental/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/02/aprenda-a-ouvir-o-seu-corpo/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/02/fitness/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/2019/08/02/bons-sonos/',
	'https://wwa.tokiomarine.com.br/vidasaudavel/'
];        
            
$arraypara = [
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/seguro-vida-mulher/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/cancer-colorretal/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/relogio-biologico/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/esteira-exercicios-em-casa/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/mulheres-luta-pela-igualdade/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/beneficios-propolis/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/dicionario-segures/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/pular-corda/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/ler/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/emocional-na-pandemia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/fone-de-ouvido/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/acucar-faz-mal/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/planejamento-financeiro/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/previna-se-da-dengue/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/meditacao/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/aplicativos-de-exercicios/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/sem-perder-o-foco/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/como-desinchar/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/bicicleta-ergometrica/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/excessos-de-fim-de-ano-2/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/check-up-concorra/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/minimalismo/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/doacoes-na-pandemia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/dezembro-laranja-prevencao/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/doencas-que-mais-matam/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/diabete-azul/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/exercicios-abdominais/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/doe-orgaos-salve-vidas/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/omega-3-gorduras-essenciais/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/novembro-azul-2/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/outubro-rosa-2/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/ocio-produtivo/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/medicina-preventiva/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/alimentos-saudaveis-para-criancas/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/exercicios-em-familia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/seguro-vida-reserva-financeira/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/alzheimer-prevencao/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/aplicativo-vida-saudavel-saude-ao-alcance-das-maos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/vamos-falar-sobre-depressao/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/exercicio-como-remedio/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/inteligencia-emocional-sabia-como-ter/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/depressao-alimentacao-como-aliada/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/novidades-do-seguro-vida-homem/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/agosto-dourado-doe-o-seu-leite/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/pets-conforto-emocional-em-tempos-de-pandemia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/faca-alongamento-o-seu-corpo-agradece/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/vencendo-a-ansiedade-em-tempos-de-covid-19/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/vitamina-d-vitamina-do-sol/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/covid-19-medo-de-ir-ao-hospital/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/seguro-vida-pme-tokio-marine/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/aumento-do-consumo-alcool-na-pandemia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/a-danca-como-remedio/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/campanha-agasalho-solidariedade/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/alimentacao-saudavel-inverno/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/va-de-bike/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/aplicativos-para-reunioes-virtuais-covid-19/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/cobertura-seguro-vida-coronavirus/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/doe-sangue-quarentena/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/planejamento-financeiro-covid-19/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/horta-casa-apartamento/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/telemedicina-einstein-conecta/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/alcool-gel-cuidado-acidentes/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/covid-19-cuidados-bem-estar/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/mascaras-protecao-duvidas/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/intestino-saudavel-fortalecimento-imunologico/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/yoga-corpo-mente-quarentena/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/seguro-vida-individual-tokio-marine-beneficios-ate-para-voce-que-esta-em-casa/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/saude-mental-em-tempos-de-quarentena/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/quarentena-como-dar-continuidade-ao-ensino-das-criancas/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/fique-em-casa-na-quarentena-mas-nao-fique-parado/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/home-office-na-quarentena/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/os-campeoes-da-imunidade-na-quarentena/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/transito-como-amenizar-os-efeitos-colaterais-causados-pelo-tempo-dentro-do-carro/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/beneficios-do-crossfit/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/como-tornar-a-alimentacao-saudavel-atrativa-para-as-criancas/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/transtorno-de-ansiedade-generalizada/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/prevencao-de-infeccoes-comuns-no-brasil/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/no-mes-da-mulher-reforcamos-as-grandes-conquistas-e-a-luta-por-igualdade-de-direitos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/einstein-conecta/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/fevereiro-roxo/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/caminhe-a-saude-agradece/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/a-musica-como-remedio/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/voce-esta-interessado-em-investir/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/carnaval-alimente-se-bem-para-cair-na-folia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/escola-segurada-seu-filho-protegido/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/cardapio-de-verao-2/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/os-beneficios-do-hobby/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/mergulhar-e-divertido-mas-e-coisa-seria/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/mindfulness/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/sarampo-e-caxumba-prevenir-e-o-melhor-remedio/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/voce-sabia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/de-olho-na-gordura-visceral/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/mes-da-luta-contra-a-aids/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/aproveite-a-praia-para-se-exercitar/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/metas-de-fim-de-ano/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/excessos-de-fim-de-ano/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/sete-bons-motivos-para-contratar-um-seguro/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/novembro-azul/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/a-importancia-de-dormir-bem/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/spinning/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/vencendo-a-compulsao-alimentar/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/as-maravilhas-da-dieta-mediterranea/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/vida-individual-e-vida-em-grupo/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/outubro-rosa/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/estendendo-a-mao/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/a-importancia-da-musculacao-ao-longo-da-vida/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/viver-conectado-interfere-no-seu-bem-estar/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/sodio-ele-e-necessario-sim/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/7-mitos-comuns-sobre-seguro-de-vida/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/21-de-setembro-dia-mundial-da-doenca-de-alzheimer/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/combate-ao-tabagismo/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/personal-trainer/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/sindrome-de-burnout/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/carboidrato-voce-pode-e-deve-comer/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/tokio-marine-acidentes-pessoais-escolar/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/seguro-de-vida-mulher/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/seguro-de-vida-individual/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/recolocacao-profissional-e-assistencia-em-decorrencia-de-atos-violentos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/vida-homem/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/inclusao-automatica-dos-filhos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/tokio-marine-acidentes-pessoais-individual/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/maio-amarelo-por-uma-nova-forma-de-encarar-o-transito/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/doar-sangue-um-ato-de-amor/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/fevereiro-e-mes-de-combate-ao-alcoolismo/',
	'https://blog.tokiomarine.com.br/vida-saudavel/voce-sabia/vida-em-grupo-pequenas-e-medias-empresas/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/a-importancia-do-check-up-prevencao-e-cura/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/de-olho-no-outubro-rosa/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/dezembro-laranja-protecao-da-pele-e-coisa-seria/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/doe-sangue-voce-pode-salvar-uma-vida/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/medicina-preventiva-a-medicina-do-futuro/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/hipertensao-uma-doenca-cada-vez-mais-comum/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/tolerancia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/comprometimento-com-a-saude/',
	'https://blog.tokiomarine.com.br/vida-saudavel/saude-e-prevencao/envelhecer-bem/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/o-doce-poder-do-elogio-e-da-gratidao/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/1o-de-dezembro/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/outubro-mes-do-combate-a-obesidade/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/8-de-marco/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/historias-inspiradoras/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/planejamento-financeiro-familiar/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/a-importancia-da-consulta-medica-antes-da-academia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/atitude/os-habitos-que-construimos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/agua-e-vida/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/intolerancia-a-lactose/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/ceia-de-natal-uma-mesa-repleta-de-tradicoes/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/cardapio-de-verao/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/alimentos-termogenicos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/mitos-e-verdades-sobre-a-gordura/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/obesidade-infantil-arme-se-contra-ela/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/o-prato-ideal/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/restricoes-alimentares-modismos-ou-verdade/',
	'https://blog.tokiomarine.com.br/vida-saudavel/alimentacao/frutas-a-farmacia-em-casa/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/exercicio-em-grupo-e-melhor/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/natacao-descubra-bons-motivos-para-correr-para-a-piscina/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/esportes-de-verao-pratique-sem-sustos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/escolhendo-a-academia/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/exercicios-ao-ar-livre/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/pilates/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/alongue-se/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/conheca-os-beneficios-dos-exercicios-funcionais/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/todo-mundo-tem-dez-minutos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/sua-excelencia-o-colaborador/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/maio-mes-de-todas-as-maes/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/por-que-viajar-faz-bem-a-saude/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/meio-ambiente-o-que-podemos-fazer-por-ele/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/declare-guerra-ao-estresse/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/seu-animal-de-estimacao-faz-bem-a-saude/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/o-poder-das-confraternizacoes-de-fim-de-ano/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/precisamos-falar-sobre-depressao/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/cuidando-da-sua-saude-mental/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/aprenda-a-ouvir-o-seu-corpo/',
	'https://blog.tokiomarine.com.br/vida-saudavel/fitness/fitness/',
	'https://blog.tokiomarine.com.br/vida-saudavel/qualidade-de-vida/bons-sonos/',
	'https://blog.tokiomarine.com.br/vida-saudavel/'
];
	$URL_ATUAL= "https://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
	$key = array_search($URL_ATUAL, $arrayde);
	$destino = $arraypara[$key];
	header('Location: '.$destino);
	exit;

?>

</head>

